### ISSUE TITLE
Tidak bisa install di PHP 7.3

### ISSUE THREAD

**Issue by wahidisna** [fherryfherry/super-framework-engine#28]
Code di `composer.json`

>  "php": "7.2.*|7.3.*|7.4.*|8.0.*",

Sedangkan 

> "lavary/crunz": "^3.0",

minimal harus menggunakan PHP versi [7.4](https://github.com/lavary/crunz/pull/349)

Bisakah paket lavary/crunz didowngrade ke versi 2?

Ketika install superframework menggunakan composer selalu gagal karena paket lavary/crunz

Terima kasih

**Comment by fherryfherry** [comment]
> Code di `composer.json`
> 
> > "php": "7.2._|7.3._|7.4._|8.0._",
> 
> Sedangkan
> 
> > "lavary/crunz": "^3.0",
> 
> minimal harus menggunakan PHP versi [7.4](https://github.com/lavary/crunz/pull/349)
> 
> Bisakah paket lavary/crunz didowngrade ke versi 2?
> 
> Ketika install superframework menggunakan composer selalu gagal karena paket lavary/crunz
> 
> Terima kasih

Ah okay bisa bisa
